version: '3'
services:
    nginx:
        image: nginx:latest
        container_name: 'nginx'
        working_dir: /srv
        networks:
            - network
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - "${APP_ROOT_DIR}:/srv"
            - "./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
        depends_on:
            - php
    php:
        build: ./docker/php
        environment:
            XDEBUG_CONFIG: remote_host=${REMOTE_HOST}
            PHP_IDE_CONFIG: serverName=${APP_HOST}
        container_name: 'php'
        working_dir: /srv
        networks:
            - network
        volumes:
            - "${APP_ROOT_DIR}:/srv"
        depends_on:
            - database
    database:
        volumes:
            - "mysql_data:/var/lib/mysql"
            - "mysql_log:/var/log/mysql"
        build: ./docker/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASS}
            MYSQL_DATABASE:      ${DB_NAME}
            MYSQL_USER:          ${DB_USER}
            MYSQL_PASSWORD:      ${DB_PASS}
        container_name: 'database'
        working_dir: /srv
        networks:
            - network
        ports:
            - "3306:3306"

volumes:
    mysql_data:
        driver: local
    mysql_log:
        driver: local

networks:
    network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet:  ${DOCKER_SUBNET}
