version: '3'
services:
    nginx:
        image: nginx:latest
        container_name: 'nginx'
        working_dir: /srv
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - "${APP_ROOT_DIR}:/srv"
            - "./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
    php:
        build: ./docker/php
        environment:
            XDEBUG_CONFIG: remote_host=${REMOTE_HOST}
            PHP_IDE_CONFIG: serverName=${APP_HOST}
        container_name: 'php'
        working_dir: /srv
        volumes:
            - "${APP_ROOT_DIR}:/srv"
    database:
        image: percona:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASS}
            MYSQL_DATABASE:      ${DB_NAME}
            MYSQL_USER:          ${DB_USER}
            MYSQL_PASSWORD:      ${DB_PASS}
        container_name: 'database'
        working_dir: /srv
        ports:
            - "3306:3306"
