App\Entity\UserText:
    type: entity
    table: user_text

    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        text:
            type: string
            nullable: false
    manyToOne:
        user:
            targetEntity: App\Entity\User
            joinColumn:
                nullable: false
                name: user_id
                referencedColumnName: id