App\Entity\User:
    type: entity
    table: user

    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        userName:
            type: string
            nullable: false
        email:
            type: string
            nullable: false
        homepage:
            type: string
            nullable: true
